name: "Automating Image Classification with Microsoft Azure Custom Vision Training and Prediction"
description: "Get your model published using this action"
author: "Mritunjay Sharma"

inputs:
  tags:
    description: "Allow user to enter tags for classification"
    required: true
  tagsVar:
    description: "The file name patter used"
    requried: true
  trainSize:
    description: "The training size of each tag"
    required: true
  endpoint:
    description: "The endpoint required to connect with Azure Custom Vision"
    required: true
  trainingKey: 
    description: "The training key for Azure Custom Vision Service"
    required: true
  predictionKey:
    description: "The prediction key for Azure Custom Vision Service"
    required: true
  predictionResourceid:
    description: "The Prediction Source ID for Azure Custom Vision Service"
    required: true

outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'box'
  color: 'blue'
